<?php

/**
 * @file
 * Module file for the Range Slider module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function range_slider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.range_slider':
      $text = file_get_contents(dirname(__FILE__) . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      // Use the Markdown filter to render the README.
      $filter_manager = \Drupal::service('plugin.manager.filter');
      $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
      $config = ['settings' => $settings];
      $filter = $filter_manager->createInstance('markdown', $config);
      return $filter->process($text, 'en');
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function range_slider_theme() {
  return [
    'range_slider' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_element_info_alter().
 */
function range_slider_element_info_alter(array &$info) {
  $info['range_slider']['#theme'] = 'range_slider';
}
